{{- if .Values.backend.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secretName | quote }}
  labels:
    app.kubernetes.io/name: chess-game
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  JWT_SECRET: ""
  EMAIL_USER: ""
  EMAIL_PASS: ""
  RECAPTCHA_SECRET_KEY: ""
{{- end }}