apiVersion: v1
kind: Service
metadata:
  name: chess-backend
  labels:
    app.kubernetes.io/name: chess-game
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: chess-backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
