apiVersion: v1
kind: Service
metadata:
  name: chess-frontend
  labels:
    app.kubernetes.io/name: chess-game
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  selector:
    app: chess-frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
