apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-frontend
  labels:
    app.kubernetes.io/name: chess-game
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: chess-frontend
  template:
    metadata:
      labels:
        app: chess-frontend
        app.kubernetes.io/name: chess-game
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: chess-frontend
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
