backend:
  image: 855409827685.dkr.ecr.ap-southeast-1.amazonaws.com/chess-backend
  tag: latest
  replicaCount: 1
  service:
    port: 5000
  secretName: chess-backend-secret
  createSecret: false
  env:
    NODE_ENV: production
    PORT: "5000"
    MONGODB_URI: mongodb://mongo:27017/chess_game
    CLIENT_URL: http://chess-game.local

frontend:
  image: 855409827685.dkr.ecr.ap-southeast-1.amazonaws.com/chess-frontend
  tag: latest
  replicaCount: 1
  service:
    port: 80
    type: LoadBalancer

mongo:
  image: mongo:6
  persistence:
    enabled: true
    size: 5Gi

ingress:
  enabled: false
  className: "nginx"
  host: chess-game.local

prometheus:
  enabled: true
  scrapePath: /metrics

alerts:
  enabled: true
  discordWebhook: "https://discord.com/api/webhooks/1442809540503666760/HwffLokOII8JYaF3ugt4cPHuOsnoJFRYcdBk8T4RyG1KK0_KeVp5uTm3TFbWk535VGCm"
